### ISSUE TITLE
Prevent non-contiguous version ranges?

### ISSUE THREAD

**Issue by tfausak** [haskell/pvp#13]
The spec does not require version components to go up by 1. It only requires that they increase. So it’s perfectly fine to go from version 1.2.3 to 4.0.0. This is not necessarily a problem, but it is potentially confusing.

**Comment by bergmark** [comment]
Do you have an example on how this has/could cause issues? There will always be at least 4 possible next versions: `A+1.B.C.D`, `A.B+1.C.D`, et.c. So clients will always have to look up what the new version is. Similar to the fairbairn threshold; Does the cost of having to specify/remember this rule outweigh the benefit of having it in place?

**Comment by hvr** [comment]
Fwiw, even if we required this, we'd still end up with non-contigous version ranges: After all, even if you know that your package works with 1.2.5 and 1.3.2 (because those are the ones you have actually validated), then without additional knowledge, the resulting inferred range is `^>= 1.2.5 || ^>= 1.3.2` in the new syntax (which desugars to `(>= 1.2.5 && < 1.3) || (>= 1.3.2 && < 1.4)` in legacy syntax). That range could in theory be grown in a safe way (see also the related WIP #10 issue) in a machine-testable way up to `>= 1.2.0 && < 1.4` (assuming there exists versions 1.2.0 and 1.3.0 and those still compile successfully). But in generall it won't be possible; nor should there be any provision in the PVP to take into account the temporal dimension; the PVP in its current form has the desirable property of not taking into account the time dimension, the PVP simply specifies a relationship between version numbers and the APIs they identify.

**Comment by phadej** [comment]
Also e.g. Cabal has odd development versions, and maintainers are atm free to add additional semantics to the version components e.g. 1.2.3.20161229 or 1.2.3.4.5.6 where last three components are vendored lib version. It's not forbidden to release packages with smaller versions than already have been released. I don't see benefit in proposal over removed freedom

**Comment by tfausak** [comment]
Is that new syntax defined somewhere? I am keenly aware that the PVP is not SemVer, but SemVer defines some good range operators: https://docs.npmjs.com/misc/semver#ranges

I don't have any examples of how this could cause a problem. I admitted that I merely see this as confusing rather than problematic.

**Comment by hvr** [comment]
@tfausak It's the rather recent "caret" syntax which is [described here](http://cabal.readthedocs.io/en/latest/developing-packages.html?highlight=caret#pkg-field-build-depends), and it was in fact inspired by the kind of syntax-sugar other ecosystems (npm,bower,ruby,php,python) operating on version ranges have in their toolset (or plan to)

**Comment by treeowl** [comment]
I also see no substantial benefit to be gained from this restriction. Note that even if a version range starts out contiguous, it may effectively cease to be so as a result of version deprecation.

**Comment by ekmett** [comment]
👎 from me. 

I'll often bump several package versions together to a common 'shared' version when they all undergo a major version bump together and are intended to work together. It is much easier to keep track of 'version 4.10' for a half-dozen packages than 4.4.3 for this one, 4.6 for that one...

**Comment by frasertweedale** [comment]
:-1: from me too.

I sometimes base library versions of revision numbers or release year/month of standards or specifications.  These don't always go up by one.  (Or even if they do, some revisions require updates to the library, and some do not).

Can we close this one now?
